name: Deploy Updated Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Detect changes in Lambda functions
        id: changes
        run: |
          echo "Checking changes in lambda folders..."

          # Check if viewCounter folder changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^lambda/viewCounter/'; then
            echo "viewCounter_changed=true" >> $GITHUB_OUTPUT
          else
            echo "viewCounter_changed=false" >> $GITHUB_OUTPUT
          fi

          # Check if contactForm folder changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^lambda/contactForm/'; then
            echo "contactForm_changed=true" >> $GITHUB_OUTPUT
          else
            echo "contactForm_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy UpdatePortfolioViewCounter Lambda
        if: steps.changes.outputs.viewCounter_changed == 'true'
        run: |
          echo "Deploying UpdatePortfolioViewCounter Lambda function"
          cd lambda/viewCounter
          zip -r function.zip .
          aws lambda update-function-code --function-name UpdatePortfolioViewCounter --zip-file fileb://function.zip

      - name: Deploy PortfolioContact Lambda
        if: steps.changes.outputs.contactForm_changed == 'true'
        run: |
          echo "Deploying PortfolioContact Lambda function"
          cd lambda/contactForm
          zip -r function.zip .
          aws lambda update-function-code --function-name PortfolioContact --zip-file fileb://function.zip
